services:
  - type: web
    name: chatbot-platform-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
